on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
name: Build and release to pypi
jobs:
  release-build:
    name: Build and upload distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pipx run build
      - name: Upload release distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
  pypi-publish:
    name: Release to pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi_publish
      url: https://pypi.org/p/wenxian
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - release-build
    permissions:
      id-token: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
